insert into pesticide (id, name, allowed) values (1, 'Gabapentin', true);
insert into pesticide (id, name, allowed) values (2, 'Clotrimazole', true);
insert into pesticide (id, name, allowed) values (3, 'Empagliflozin', true);
insert into pesticide (id, name, allowed) values (4, 'ACETAMINOPHEN, DEXTROMETHORPHAN HYDROBROMIDE, PHENYLEPHRINE HYDROCHLORIDE', true);
insert into pesticide (id, name, allowed) values (5, 'Ibutilide Fumarate', true);
insert into pesticide (id, name, allowed) values (6, 'Amitriptyline Hydrochloride', false);
insert into pesticide (id, name, allowed) values (7, 'Doxycycline Hyclate', false);
insert into pesticide (id, name, allowed) values (8, 'Sodium Chloride', true);
insert into pesticide (id, name, allowed) values (9, 'morphine sulfate', false);
insert into pesticide (id, name, allowed) values (10, 'TOPIRAMATE', true);
insert into pesticide (id, name, allowed) values (11, 'Glycerine and Phenol', true);
insert into pesticide (id, name, allowed) values (12, 'Oxymetazoline Hydrochloride', true);
insert into pesticide (id, name, allowed) values (13, 'ALUMINUM CHLOROHYDRATE', true);
insert into pesticide (id, name, allowed) values (14, 'NALBUPHINE HYDROCHLORIDE', false);
insert into pesticide (id, name, allowed) values (15, 'Ibuprofen and Diphenhydramine Citrate', true);
insert into pesticide (id, name, allowed) values (16, 'Losartan Potassium', true);
insert into pesticide (id, name, allowed) values (17, 'TITANIUM DIOXIDE, ZINC OXIDE, ARBUTIN, ADENOSINE', false);
insert into pesticide (id, name, allowed) values (18, 'SODIUM FLUORIDE', false);
insert into pesticide (id, name, allowed) values (19, 'Loperamide Hydrochloride', true);
insert into pesticide (id, name, allowed) values (20, 'Carbon Dioxide-Air Mixture', false);
insert into pesticide (id, name, allowed) values (21, 'GABAPENTIN, .GAMMA.-AMINOBUTYRIC ACID', false);
insert into pesticide (id, name, allowed) values (22, 'Ibuprofen', false);
insert into pesticide (id, name, allowed) values (23, 'Clindamycin Hydrochloride', false);
insert into pesticide (id, name, allowed) values (24, 'bepotastine besilate', true);
insert into pesticide (id, name, allowed) values (25, 'Italian Rye Grass', true);
insert into pesticide (id, name, allowed) values (26, 'diclofenac sodium and misoprostol', true);
insert into pesticide (id, name, allowed) values (27, 'pramipexole dihydrochloride', true);
insert into pesticide (id, name, allowed) values (28, 'Capsaicin', false);
insert into pesticide (id, name, allowed) values (29, 'Carbamazepine', false);
insert into pesticide (id, name, allowed) values (30, 'Pyrrole', true);
insert into pesticide (id, name, allowed) values (31, 'HYDROMORPHONE HYDROCHLORIDE', false);
insert into pesticide (id, name, allowed) values (32, 'Ranitidine Hydrochloride', true);
insert into pesticide (id, name, allowed) values (33, 'Hydrocortisone', true);
insert into pesticide (id, name, allowed) values (34, 'Benzalkonium chloride', false);
insert into pesticide (id, name, allowed) values (35, 'zonisamide', true);
insert into pesticide (id, name, allowed) values (36, 'Mannitol', true);
insert into pesticide (id, name, allowed) values (37, 'Chlorpheniramine Maleate and Dextromethorphan Hydrobromide', false);
insert into pesticide (id, name, allowed) values (38, 'Hydrocodone Bitartrate and Acetaminophen', true);
insert into pesticide (id, name, allowed) values (39, 'OCTINOXATE and TITANIUM DIOXIDE', true);
insert into pesticide (id, name, allowed) values (40, 'Etodolac', false);
insert into pesticide (id, name, allowed) values (41, 'Furosemide', false);
insert into pesticide (id, name, allowed) values (42, 'Glimepiride', false);
insert into pesticide (id, name, allowed) values (43, 'Sodium Fluoride', true);
insert into pesticide (id, name, allowed) values (44, 'paroxetine hydrochloride hemihydrate', true);
insert into pesticide (id, name, allowed) values (45, 'Prednisone', true);
insert into pesticide (id, name, allowed) values (46, 'HYPROMELLOSE', false);
insert into pesticide (id, name, allowed) values (47, 'SALICYLIC ACID', false);
insert into pesticide (id, name, allowed) values (48, 'OCTINOXATE, OCTISALATE, AVOBENZONE, OCTOCRYLENE', true);
insert into pesticide (id, name, allowed) values (49, 'German Cockroach', false);
insert into pesticide (id, name, allowed) values (50, 'Alcohol', false);
insert into pesticide (id, name, allowed) values (51, 'Potassium Chloride', true);
insert into pesticide (id, name, allowed) values (52, 'AVOBENZONE, OCTOCRYLENE, OXYBENZONE', false);
insert into pesticide (id, name, allowed) values (53, 'SODIUM BICARBONATE', false);
insert into pesticide (id, name, allowed) values (54, 'Ziprasidone hydrochloride', true);
insert into pesticide (id, name, allowed) values (55, 'ECHINACEA ANGUSTIFOLIA, ECHINACEA PURPUREA, ACONITUM NAPELLUS, ARNICA MONTANA, CALENDULA OFFICIANALIS, HAMAMELIS VIRGINIANA, BELLADONNA, BELLIS PERENNIS, CHAMOMILLIA, MILLEFOLIUM, HYPERICUM PERFORATUM, SYMPHYTUM OFFICINALE, COLCHICINUM, ZINGIBER OFFICINALE', true);
insert into pesticide (id, name, allowed) values (56, 'Fexofenadine Hydrochloride', true);
insert into pesticide (id, name, allowed) values (57, 'Titanium Dioxide, Zinc Oxide', false);
insert into pesticide (id, name, allowed) values (58, 'Potassium Nitrate', false);
insert into pesticide (id, name, allowed) values (59, 'Menthol', true);
insert into pesticide (id, name, allowed) values (60, 'phenylephrine hydrochloride and witch hazel', false);
insert into pesticide (id, name, allowed) values (61, 'Titanium Dioxide and Zinc Oxide', false);
insert into pesticide (id, name, allowed) values (62, 'zaleplon', false);
insert into pesticide (id, name, allowed) values (63, 'benzalkonium chloride', true);
insert into pesticide (id, name, allowed) values (64, 'furosemide', false);
insert into pesticide (id, name, allowed) values (65, 'Sodium Chloride', false);
insert into pesticide (id, name, allowed) values (66, 'paroxetine hydrochloride', false);
insert into pesticide (id, name, allowed) values (67, 'Flumazenil', false);
insert into pesticide (id, name, allowed) values (68, 'Colestipol Hydrochloride', false);
insert into pesticide (id, name, allowed) values (69, 'Guaifenesin', false);
insert into pesticide (id, name, allowed) values (70, 'Trichoderma harzianam', true);
insert into pesticide (id, name, allowed) values (71, 'Belladonna 30C HPUS, Ferrum phosphoricum 12 X HPUS, Hepar sulphuris 12C HPUS, Mercurius solubilis 12C HPUS, Salicylicum acidum 6C HPUS, Silicea 6X HPUS', false);
insert into pesticide (id, name, allowed) values (72, 'Apis Mellifica, Carbolicum Acidum, Ledum Palustre', true);
insert into pesticide (id, name, allowed) values (73, 'isotretinoin', true);
insert into pesticide (id, name, allowed) values (74, '.beta.-carotene, ascorbic acid, cholecalciferol, .alpha.-tocopherol acetate, dl-, thiamine mononitrate, riboflavin, niacinamide, pyridoxine hydrochloride, folic acid, cyanocobalamin, calcium carbonate, ferrous fumarate, potassium iodide and zinc oxide', true);
insert into pesticide (id, name, allowed) values (75, 'Asterias rubens, Aur. met., Belladonna, Benzoicum acidum, Berber. vulg., Bryonia, Calc. carb., Cantharis, Ceanothus, Chelidonium majus, Chionanthus virginica, Cinchona, Dioscorea, Iris versicolor, Nat. carb., Nux vom., Ptelea, Carduus mar., Echinacea, Solidago, Taraxacum', false);
insert into pesticide (id, name, allowed) values (76, 'Simvastatin', false);
insert into pesticide (id, name, allowed) values (77, 'Doxepin Hydrochloride', true);
insert into pesticide (id, name, allowed) values (78, 'ENSULIZOLE, HOMOSALATE, OCTINOXATE, OXYBENZONE', false);
insert into pesticide (id, name, allowed) values (79, 'oxygen', false);
insert into pesticide (id, name, allowed) values (80, 'Pandanus Calc. Carb', true);
insert into pesticide (id, name, allowed) values (81, 'Octreotide Acetate', true);
insert into pesticide (id, name, allowed) values (82, 'FENTANYL', true);
insert into pesticide (id, name, allowed) values (83, 'Gabapentin', false);
insert into pesticide (id, name, allowed) values (84, 'Metoprolol succinate', false);
insert into pesticide (id, name, allowed) values (85, 'Anticoagulant Citrate Phosphate Dextrose (CPD) Solution and ADSOL Preservation Solution', false);
insert into pesticide (id, name, allowed) values (86, 'Citalopram', false);
insert into pesticide (id, name, allowed) values (87, 'Coal Tar', true);
insert into pesticide (id, name, allowed) values (88, 'Venlafaxine Hydrochloride', false);
insert into pesticide (id, name, allowed) values (89, 'CAPTORPIL', false);
insert into pesticide (id, name, allowed) values (90, 'Acetaminophen', false);
insert into pesticide (id, name, allowed) values (91, 'Menthol', true);
insert into pesticide (id, name, allowed) values (92, 'Alcohol', true);
insert into pesticide (id, name, allowed) values (93, 'Eszopiclone', true);
insert into pesticide (id, name, allowed) values (94, 'Meclizine Hydrochloride', false);
insert into pesticide (id, name, allowed) values (95, 'Cyclobenzaprine Hydrochloride', false);
insert into pesticide (id, name, allowed) values (96, 'Penicillium chrysogenum', true);
insert into pesticide (id, name, allowed) values (97, 'Epinephrine', false);
insert into pesticide (id, name, allowed) values (98, 'Cashew', false);
insert into pesticide (id, name, allowed) values (99, 'Captopril', true);
insert into pesticide (id, name, allowed) values (100, 'TRICLOSAN', true);
insert into pesticide (id, name, allowed) values (101, 'bacitracin, neomycin, polymyxin B', false);
insert into pesticide (id, name, allowed) values (102, 'TITANIUM DIOXIDE, ZINC OXIDE', false);
insert into pesticide (id, name, allowed) values (103, 'CAMPHOR (NATURAL), MENTHOL', true);
insert into pesticide (id, name, allowed) values (104, 'dextromethorphan hbr, guaifenesin, phenylephrine hcl', false);
insert into pesticide (id, name, allowed) values (105, 'Gabapentin', false);
insert into pesticide (id, name, allowed) values (106, 'Leucine, Phenylalanine, Lysine, Methionine, Isoleucine, Valine, Histidine, Threonine, Tryptophan, Alanine, Glycine, Arginine, Proline, Serine, Tyrosine, Sodium Acetate, Dibasic Potassium Phosphate, Ma', false);
insert into pesticide (id, name, allowed) values (107, 'Glycerin', false);
insert into pesticide (id, name, allowed) values (108, 'Fluconazole', true);
insert into pesticide (id, name, allowed) values (109, 'Sodium Acetate', false);
insert into pesticide (id, name, allowed) values (110, '.BETA.-CAROTENE, ASCORBIC ACID, CHOLECALCIFEROL, .ALPHA.-TOCOPHEROL, DL-, THIAMINE HYDROCHLORIDE, RIBOFLAVIN, NIACIN, PYRIDOXINE HYDROCHLORIDE, FOLIC ACID, HYDROXOCOBALAMIN, BIOTIN, CALCIUM PANTOTHENATE, FERROUS CYSTEINE GLYCINATE, MAGNESIUM OXIDE, ZINC OXIDE, CUPRIC OXIDE, and SODIUM FLUORIDE', true);
insert into pesticide (id, name, allowed) values (111, 'Acetaminophen', false);
insert into pesticide (id, name, allowed) values (112, 'Levothyroxine Sodium', true);
insert into pesticide (id, name, allowed) values (113, 'LEVOTHYROXINE SODIUM', false);
insert into pesticide (id, name, allowed) values (114, 'Ketorolac Tromethamine', false);
insert into pesticide (id, name, allowed) values (115, 'OCTINOXATE and TITANIUM DIOXIDE', false);
insert into pesticide (id, name, allowed) values (116, 'DEXTROAMPHETAMINE SACCHARATE, AMPHETAMINE ASPARTATE, DEXTROAMPHETAMINE SULFATE AND AMPHETAMINE SUFLATE', true);
insert into pesticide (id, name, allowed) values (117, 'Pollens - Weeds, Marshelder/Poverty Mix', false);
insert into pesticide (id, name, allowed) values (118, 'Octinoxate, TITANIUM DIOXIDE, and ZINC OXIDE', false);
insert into pesticide (id, name, allowed) values (119, 'Zinc oxide', true);
insert into pesticide (id, name, allowed) values (120, 'DEXTROMETHORPHAN HYDROBROMIDE, GUAIFENESIN, and PHENYLEPHRINE HYDROCHLORIDE', true);
insert into pesticide (id, name, allowed) values (121, 'Bryonia alba, Drosera rotundifolia, Ipecacuanha', false);
insert into pesticide (id, name, allowed) values (122, 'CHLOROXYLENOL', true);
insert into pesticide (id, name, allowed) values (123, 'Cladosporium Sphaerospermum Hormodendrum Hordei', false);
insert into pesticide (id, name, allowed) values (124, 'Eucalyptol, menthol, methyl salicylate, thymol', true);
insert into pesticide (id, name, allowed) values (125, 'Acyclovir', false);
insert into pesticide (id, name, allowed) values (126, 'Lidocaine Hydrochloride and Epinephrine Bitartrate', true);
insert into pesticide (id, name, allowed) values (127, 'ethylhexl methoxycinnamate', false);
insert into pesticide (id, name, allowed) values (128, 'ATORVASTATIN CALCIUM', false);
insert into pesticide (id, name, allowed) values (129, 'Titanium Dioxide, OCTINOXATE', true);
insert into pesticide (id, name, allowed) values (130, 'Oxygen', false);
insert into pesticide (id, name, allowed) values (131, 'camphor, menthol', true);
insert into pesticide (id, name, allowed) values (132, 'terconazole', true);
insert into pesticide (id, name, allowed) values (133, 'Cyclobenzaprine Hydrochloride', true);
insert into pesticide (id, name, allowed) values (134, 'Losartan Potassium and Hydrochlorothiazide', true);
insert into pesticide (id, name, allowed) values (135, 'LISINOPRIL', true);
insert into pesticide (id, name, allowed) values (136, 'Fluphenazine Decanoate', false);
insert into pesticide (id, name, allowed) values (137, 'Acetaminophen', true);
insert into pesticide (id, name, allowed) values (138, 'nifedipine', true);
insert into pesticide (id, name, allowed) values (139, 'Bacitracin Zinc, Neomycin Sulfate, Polymyxin B Sulfate, and Pramoxine Hydrochloride', false);
insert into pesticide (id, name, allowed) values (140, 'IBUPROFEN', true);
insert into pesticide (id, name, allowed) values (141, 'SODIUM FLUORIDE', true);
insert into pesticide (id, name, allowed) values (142, 'BENZALKONIUM CHLORIDE', true);
insert into pesticide (id, name, allowed) values (143, 'Felodipine', false);
insert into pesticide (id, name, allowed) values (144, 'oxycodone hydrochloride', true);
insert into pesticide (id, name, allowed) values (145, 'Octinoxate and Titanium dioxide', true);
insert into pesticide (id, name, allowed) values (146, 'POVIDONE-IODINE', true);
insert into pesticide (id, name, allowed) values (147, 'Oxybutynin Chloride', false);
insert into pesticide (id, name, allowed) values (148, 'Ibuprofen', false);
insert into pesticide (id, name, allowed) values (149, 'Benzocaine', true);
insert into pesticide (id, name, allowed) values (150, 'fosamprenavir calcium', false);
