insert into plantation (id, id_user, name, address, city, state) values (1, 36, 'Texas Bristlegrass', '591 Meadow Valley Junction', 'Quintong', null);
insert into plantation (id, id_user, name, address, city, state) values (2, 37, 'Painted Milkvetch', '1 New Castle Junction', 'Zhenqiao', null);
insert into plantation (id, id_user, name, address, city, state) values (3, 101, 'Tehachapi Linanthus', '232 Pleasure Pass', 'Kamyshin', null);
insert into plantation (id, id_user, name, address, city, state) values (4, 120, 'Inyo Gilia', '39 Oneill Way', 'Coishco', null);
insert into plantation (id, id_user, name, address, city, state) values (5, 283, 'Tolmie Star-tulip', '1 Fieldstone Alley', 'Cayenne', 'Guyane');
insert into plantation (id, id_user, name, address, city, state) values (6, 72, 'American Mannagrass', '0 Marcy Terrace', 'Mpigi', null);
insert into plantation (id, id_user, name, address, city, state) values (7, 261, 'Cotoneaster', '395 Summer Ridge Street', 'Aldeia de Além', 'Santarém');
insert into plantation (id, id_user, name, address, city, state) values (8, 196, 'Turkey Oak', '4 Starling Point', 'Karpushikha', null);
insert into plantation (id, id_user, name, address, city, state) values (9, 259, 'Orange Lichen', '92522 Springview Pass', 'Taiyuan', null);
insert into plantation (id, id_user, name, address, city, state) values (10, 5, 'Japanese Apricot', '88 Delladonna Circle', 'Janakkala', null);
insert into plantation (id, id_user, name, address, city, state) values (11, 165, 'Oregon Whitetop Aster', '34154 Lerdahl Alley', 'Samara', null);
insert into plantation (id, id_user, name, address, city, state) values (12, 285, 'Nail Lichen', '20601 Sullivan Court', 'Rassvet', null);
insert into plantation (id, id_user, name, address, city, state) values (13, 144, 'Ballhead Sandwort', '2992 Dakota Alley', 'Pelópion', null);
insert into plantation (id, id_user, name, address, city, state) values (14, 202, 'Tolmie''s Goldenrod', '294 Ohio Point', 'Shilovo', null);
insert into plantation (id, id_user, name, address, city, state) values (15, 82, 'Dwarf Greasebush', '700 Walton Crossing', 'Ospina', null);
insert into plantation (id, id_user, name, address, city, state) values (16, 61, 'Orangeberry Nightshade', '94 Dayton Alley', 'Libertad', null);
insert into plantation (id, id_user, name, address, city, state) values (17, 151, 'Modoc Frasera', '28455 Kropf Drive', 'Ryūgasaki', null);
insert into plantation (id, id_user, name, address, city, state) values (18, 15, 'Punctelia', '15 Veith Junction', 'Baláo', null);
insert into plantation (id, id_user, name, address, city, state) values (19, 29, 'Creeping Sage', '54119 Bonner Trail', 'Hamburg', 'Hamburg');
insert into plantation (id, id_user, name, address, city, state) values (20, 89, 'Calico Aster', '1 Northview Junction', 'Gerdu', null);
insert into plantation (id, id_user, name, address, city, state) values (21, 176, 'Dollarjoint Pricklypear', '2 Forest Dale Plaza', 'Maunggora', null);
insert into plantation (id, id_user, name, address, city, state) values (22, 15, 'Herman''s Dwarf Rush', '38 Artisan Plaza', 'Itaocara', null);
insert into plantation (id, id_user, name, address, city, state) values (23, 145, 'Acaulon Moss', '3588 Melody Street', 'Meiktila', null);
insert into plantation (id, id_user, name, address, city, state) values (24, 270, 'Pterogonium Moss', '374 Sheridan Pass', 'Filipowice', null);
insert into plantation (id, id_user, name, address, city, state) values (25, 126, 'Avocado', '3 Gina Street', 'Wuyang', null);
insert into plantation (id, id_user, name, address, city, state) values (26, 288, 'Prairie Rosinweed', '31838 Village Green Parkway', 'Seattle', 'Washington');
insert into plantation (id, id_user, name, address, city, state) values (27, 188, 'Sheathed Wildparsley', '5419 Swallow Lane', 'Gori', null);
insert into plantation (id, id_user, name, address, city, state) values (28, 89, 'Rough Panicgrass', '003 Pond Court', 'Husów', null);
insert into plantation (id, id_user, name, address, city, state) values (29, 66, 'Showy Goldenrod', '789 Warbler Junction', 'Cherëmushki', null);
insert into plantation (id, id_user, name, address, city, state) values (30, 82, 'Mendocino Ceanothus', '41 Birchwood Way', 'General San Martín', null);
insert into plantation (id, id_user, name, address, city, state) values (31, 253, 'Eastern Wahoo', '94293 Sachs Terrace', 'Cinyumput', null);
insert into plantation (id, id_user, name, address, city, state) values (32, 77, 'Cypress-pine', '350 Donald Alley', 'Tambarangan', null);
insert into plantation (id, id_user, name, address, city, state) values (33, 97, 'Manyawn Pricklyleaf', '788 Elgar Trail', 'Upi', null);
insert into plantation (id, id_user, name, address, city, state) values (34, 186, 'Spreading Snakeherb', '61520 Kennedy Center', 'Korobitsyno', null);
insert into plantation (id, id_user, name, address, city, state) values (35, 213, 'Sphaerellothecium Lichen', '74 Oxford Hill', 'Náklo', null);
insert into plantation (id, id_user, name, address, city, state) values (36, 124, 'Marsh''s Bluegrass', '479 Cardinal Park', 'San Sebastian', 'Oaxaca');
insert into plantation (id, id_user, name, address, city, state) values (37, 268, 'Tinantia', '4281 Moulton Road', 'Nangalimang', null);
insert into plantation (id, id_user, name, address, city, state) values (38, 57, 'Guaje', '940 Stone Corner Lane', 'Géfyra', null);
insert into plantation (id, id_user, name, address, city, state) values (39, 19, 'Hylocomiastrum Moss', '7215 Towne Drive', 'Anjihai', null);
insert into plantation (id, id_user, name, address, city, state) values (40, 139, 'Twisselmann''s Threadplant', '9 Hazelcrest Way', 'São João dos Montes', 'Lisboa');
insert into plantation (id, id_user, name, address, city, state) values (41, 91, 'Mycocalicium Lichen', '5 Annamark Crossing', 'Argungu', null);
insert into plantation (id, id_user, name, address, city, state) values (42, 214, '''oha Kepau', '17597 Hovde Junction', 'Jaru', null);
insert into plantation (id, id_user, name, address, city, state) values (43, 19, 'Whiterim Scurfpea', '5 Blue Bill Park Terrace', 'Al Mazra‘ah', null);
insert into plantation (id, id_user, name, address, city, state) values (44, 78, 'Whiteray Pygmydaisy', '995 Sunfield Parkway', 'Gabi', null);
insert into plantation (id, id_user, name, address, city, state) values (45, 111, 'Chinese Boxorange', '1 Fairview Center', 'Xishui', null);
insert into plantation (id, id_user, name, address, city, state) values (46, 6, 'Disc Lichen', '695 Arapahoe Place', 'Rajapeni', null);
insert into plantation (id, id_user, name, address, city, state) values (47, 278, 'Lobed Tickseed', '62378 Westport Circle', 'Härnösand', 'Västernorrland');
insert into plantation (id, id_user, name, address, city, state) values (48, 25, 'Hermit Milkvetch', '3925 Comanche Place', 'Dahu', null);
insert into plantation (id, id_user, name, address, city, state) values (49, 188, 'Elusive Jacob''s-ladder', '834 Arizona Street', 'Baní', null);
insert into plantation (id, id_user, name, address, city, state) values (50, 72, 'Lehua Papa', '10 Golf Course Avenue', 'Oslo', 'Oslo');
insert into plantation (id, id_user, name, address, city, state) values (51, 279, 'Hypotrachyna Lichen', '21 Schlimgen Center', 'Kuwayris Sharqī', null);
insert into plantation (id, id_user, name, address, city, state) values (52, 107, 'Shortray Rockdaisy', '9415 Carioca Parkway', 'Ma’an', null);
insert into plantation (id, id_user, name, address, city, state) values (53, 172, 'Shamel Ash', '18 Prairieview Place', 'Likhovskoy', null);
insert into plantation (id, id_user, name, address, city, state) values (54, 202, 'Peck''s Beardtongue', '060 Rieder Parkway', 'Idenao', null);
insert into plantation (id, id_user, name, address, city, state) values (55, 135, 'Cracked Lichen', '73697 Debs Way', 'Raffingora', null);
insert into plantation (id, id_user, name, address, city, state) values (56, 192, 'Bearded Prairie Clover', '722 Village Park', 'Luleå', 'Norrbotten');
insert into plantation (id, id_user, name, address, city, state) values (57, 177, 'Blackcurly Lichen', '10261 Londonderry Court', 'Stanišić', null);
insert into plantation (id, id_user, name, address, city, state) values (58, 84, 'Guadeloupe Cucumber', '837 Transport Street', 'Strachówka', null);
insert into plantation (id, id_user, name, address, city, state) values (59, 263, 'Blue-fly Honeysuckle', '28 Grover Alley', 'Talangnan', null);
insert into plantation (id, id_user, name, address, city, state) values (60, 24, 'Pallid Suncup', '4493 Kensington Crossing', 'Sacramento', 'California');
insert into plantation (id, id_user, name, address, city, state) values (61, 130, 'Whitney''s Bristleweed', '66 Rusk Center', 'Gelatik', null);
insert into plantation (id, id_user, name, address, city, state) values (62, 189, 'Orange Coneflower', '842 Arkansas Avenue', 'Pereiro', 'Viana do Castelo');
insert into plantation (id, id_user, name, address, city, state) values (63, 212, 'Sticky Blue Eyed Mary', '4260 Pankratz Crossing', 'Kota Kinabalu', 'Sabah');
insert into plantation (id, id_user, name, address, city, state) values (64, 59, 'Los Pinitos Dodder', '83 Eagan Center', 'Heyan', null);
insert into plantation (id, id_user, name, address, city, state) values (65, 215, 'Western Burning Bush', '4 Clarendon Center', 'Chaodi', null);
insert into plantation (id, id_user, name, address, city, state) values (66, 250, 'Wilson''s Bartramidula Moss', '7 Anthes Point', 'Santa María de Ipire', null);
insert into plantation (id, id_user, name, address, city, state) values (67, 98, 'Jelly Lichen', '107 Grover Alley', 'Xindong', null);
insert into plantation (id, id_user, name, address, city, state) values (68, 229, 'Garber''s Sandmat', '513 Fremont Crossing', 'Ambatondrazaka', null);
insert into plantation (id, id_user, name, address, city, state) values (69, 75, 'Grove Bluegrass', '52814 Garrison Way', 'Gambang', 'Pahang');
insert into plantation (id, id_user, name, address, city, state) values (70, 264, 'Splitleaf Gilia', '8075 Mendota Alley', 'Pengchang', null);
insert into plantation (id, id_user, name, address, city, state) values (71, 63, 'Dewey Sedge', '267 Monument Crossing', 'Nové Sedlo', null);
insert into plantation (id, id_user, name, address, city, state) values (72, 32, 'Tobacco', '2 Spohn Court', 'Chenjiatan', null);
insert into plantation (id, id_user, name, address, city, state) values (73, 48, 'West African Albizzia', '93754 Arkansas Park', 'Faranah', null);
insert into plantation (id, id_user, name, address, city, state) values (74, 143, 'Canadian Wildrye', '513 Monument Alley', 'Pasadena', 'California');
insert into plantation (id, id_user, name, address, city, state) values (75, 113, 'Phaeographis', '93119 Harper Avenue', 'Fuyang', null);
insert into plantation (id, id_user, name, address, city, state) values (76, 168, 'Purple Dropseed', '5 Little Fleur Road', 'Mavingouni', null);
insert into plantation (id, id_user, name, address, city, state) values (77, 177, 'Crater Lake Sandwort', '3737 Memorial Pass', 'Kalutara', null);
insert into plantation (id, id_user, name, address, city, state) values (78, 150, 'Hairy New York Aster', '6890 Reindahl Hill', 'Morteros', null);
insert into plantation (id, id_user, name, address, city, state) values (79, 194, 'Intermediate Cliffbrake', '1933 Commercial Alley', 'Qa‘ţabah', null);
insert into plantation (id, id_user, name, address, city, state) values (80, 212, 'Thelenella Lichen', '3 7th Street', 'Vityazevo', null);
insert into plantation (id, id_user, name, address, city, state) values (81, 278, 'Laurel-leaf Swordfern', '17518 Morningstar Place', 'Murindó', null);
insert into plantation (id, id_user, name, address, city, state) values (82, 205, 'Purplestem Angelica', '51961 Hallows Parkway', 'Shamva', null);
insert into plantation (id, id_user, name, address, city, state) values (83, 23, 'Vetivergrass', '69664 Sachtjen Alley', 'Sakassou', null);
insert into plantation (id, id_user, name, address, city, state) values (84, 284, 'Foothill Beardtongue', '54607 Miller Parkway', 'Laç', null);
insert into plantation (id, id_user, name, address, city, state) values (85, 126, 'Thicket Hogwood', '361 Reinke Terrace', 'Bobon', null);
insert into plantation (id, id_user, name, address, city, state) values (86, 139, 'Black Maple', '5441 Hollow Ridge Hill', 'Obala', null);
insert into plantation (id, id_user, name, address, city, state) values (87, 272, 'Blazing Star', '4 Roth Point', 'Kunyang', null);
insert into plantation (id, id_user, name, address, city, state) values (88, 71, 'Wild Century Plant', '27915 Hauk Road', 'Susaki', null);
insert into plantation (id, id_user, name, address, city, state) values (89, 55, 'Mildred''s Clarkia', '9 Ramsey Pass', 'Dār Kulayb', null);
insert into plantation (id, id_user, name, address, city, state) values (90, 130, 'James'' Buckwheat', '436 Summer Ridge Crossing', 'Ugbokpo', null);
insert into plantation (id, id_user, name, address, city, state) values (91, 141, 'Purplestem Beggarticks', '69 Esker Parkway', 'Chadian', null);
insert into plantation (id, id_user, name, address, city, state) values (92, 15, 'Cushion Spurge', '8 Kingsford Plaza', 'Peace River', 'Alberta');
insert into plantation (id, id_user, name, address, city, state) values (93, 180, 'Thelocarpon Lichen', '615 Sachs Parkway', 'Dukhovshchina', null);
insert into plantation (id, id_user, name, address, city, state) values (94, 144, 'San Lorenzo Milkvine', '77 Coolidge Point', 'Jefferson City', 'Missouri');
insert into plantation (id, id_user, name, address, city, state) values (95, 254, 'Uahiapele', '1 Coleman Plaza', 'Wenlin', null);
insert into plantation (id, id_user, name, address, city, state) values (96, 113, 'Inflated Grasswidow', '16 Old Shore Drive', 'Suwa', null);
insert into plantation (id, id_user, name, address, city, state) values (97, 138, 'Hybrid Oak', '38056 Bonner Alley', 'Gritsovskiy', null);
insert into plantation (id, id_user, name, address, city, state) values (98, 81, 'Rimmed Lichen', '876 Del Sol Avenue', 'Rokytne', null);
insert into plantation (id, id_user, name, address, city, state) values (99, 194, 'Pinkhead Smartweed', '12 Sugar Drive', 'Thành Phố Lạng Sơn', null);
insert into plantation (id, id_user, name, address, city, state) values (100, 260, 'Black Vetivergrass', '64187 Sugar Court', 'Grabica', null);
insert into plantation (id, id_user, name, address, city, state) values (101, 104, 'Golden Tiara Clematis', '5578 Bellgrove Point', 'Damnoen Saduak', null);
insert into plantation (id, id_user, name, address, city, state) values (102, 80, 'Camphorweed', '818 Darwin Lane', 'Pizarro', null);
insert into plantation (id, id_user, name, address, city, state) values (103, 208, 'Lori''s Columbine', '6 Hudson Center', 'Épinal', 'Lorraine');
insert into plantation (id, id_user, name, address, city, state) values (104, 125, 'Tropical Leafbract', '9 Riverside Pass', 'Katipunan', null);
insert into plantation (id, id_user, name, address, city, state) values (105, 69, 'Rose Meadowsweet', '0908 Farwell Alley', 'Hexi', null);
insert into plantation (id, id_user, name, address, city, state) values (106, 210, 'Cusick''s Stickseed', '48 Pine View Point', 'At Tibnī', null);
insert into plantation (id, id_user, name, address, city, state) values (107, 256, 'Capillary Hairsedge', '14712 Blackbird Park', 'Santa Teresa', null);
insert into plantation (id, id_user, name, address, city, state) values (108, 23, 'Purpleflower Pinkroot', '87 Grasskamp Place', 'Caen', 'Basse-Normandie');
insert into plantation (id, id_user, name, address, city, state) values (109, 95, 'Phaeocalicium Lichen', '288 Warner Point', 'Ostrožská Nová Ves', null);
insert into plantation (id, id_user, name, address, city, state) values (110, 141, 'Dogtooth Violet', '5738 Maple Way', 'Midland', 'Texas');
insert into plantation (id, id_user, name, address, city, state) values (111, 229, 'Tibey Parasito', '6072 Dwight Place', 'Sapernoye', null);
insert into plantation (id, id_user, name, address, city, state) values (112, 274, 'Hollyleaf Gilia', '87 Green Way', 'Volkhov', null);
insert into plantation (id, id_user, name, address, city, state) values (113, 124, 'Philonotis Moss', '1412 Moland Avenue', 'Padaan', null);
insert into plantation (id, id_user, name, address, city, state) values (114, 221, 'Loxospora Lichen', '7 Sachtjen Center', 'Magangué', null);
insert into plantation (id, id_user, name, address, city, state) values (115, 48, 'Hairy Chaffhead', '010 Bayside Terrace', 'Shankeng', null);
insert into plantation (id, id_user, name, address, city, state) values (116, 67, 'Common Marshmallow', '8 Green Pass', 'Tsotsin-Yurt', null);
insert into plantation (id, id_user, name, address, city, state) values (117, 281, 'Mountain Tansymustard', '0 Maple Plaza', 'Miharu', null);
insert into plantation (id, id_user, name, address, city, state) values (118, 204, 'California Goldenbanner', '0 Grover Junction', 'Cidamar', null);
insert into plantation (id, id_user, name, address, city, state) values (119, 245, 'Lemmon''s Keckiella', '08781 Anzinger Center', 'Nanterre', 'Île-de-France');
insert into plantation (id, id_user, name, address, city, state) values (120, 74, 'Amphidium Moss', '7201 Browning Drive', 'Duvergé', null);
insert into plantation (id, id_user, name, address, city, state) values (121, 82, 'Fragrant Spikesedge', '8046 Haas Drive', 'Guatraché', null);
insert into plantation (id, id_user, name, address, city, state) values (122, 277, 'Annual Marsh Elder', '56 Manufacturers Pass', 'Esquipulas', null);
insert into plantation (id, id_user, name, address, city, state) values (123, 250, 'Vente Conmigo', '3 Memorial Hill', 'Firminópolis', null);
insert into plantation (id, id_user, name, address, city, state) values (124, 232, 'Florida Jujube', '21 Monument Lane', 'Červené Pečky', null);
insert into plantation (id, id_user, name, address, city, state) values (125, 254, 'Thickleaf Drymary', '0 Muir Hill', 'Hayama', null);
insert into plantation (id, id_user, name, address, city, state) values (126, 285, 'Mahogany', '4 Prairie Rose Court', 'Kawm Ḩamādah', null);
insert into plantation (id, id_user, name, address, city, state) values (127, 44, 'Beggarticks', '5234 Farwell Avenue', 'Zaqatala', null);
insert into plantation (id, id_user, name, address, city, state) values (128, 194, 'Channel Island Poppy', '03033 Hallows Point', 'Brotas', null);
insert into plantation (id, id_user, name, address, city, state) values (129, 171, 'Oregon White Oak', '19 Riverside Crossing', 'Studzionka', null);
insert into plantation (id, id_user, name, address, city, state) values (130, 179, 'Daffodil', '718 Mccormick Plaza', 'Luhans’ke', null);
insert into plantation (id, id_user, name, address, city, state) values (131, 75, 'Parish''s Yampah', '019 Crescent Oaks Drive', 'Fangyan', null);
insert into plantation (id, id_user, name, address, city, state) values (132, 134, 'Reddish Bamboo', '1 Stang Court', 'Richmond', null);
insert into plantation (id, id_user, name, address, city, state) values (133, 168, 'Emory''s Milkvetch', '8677 Stone Corner Hill', 'Valkeakoski', null);
insert into plantation (id, id_user, name, address, city, state) values (134, 90, 'Glacier Eyebright', '23543 Westerfield Park', 'Odiongan', null);
insert into plantation (id, id_user, name, address, city, state) values (135, 205, 'Butterfly Orchid', '242 Summit Way', 'Chongxian', null);
insert into plantation (id, id_user, name, address, city, state) values (136, 66, 'Virginia Roundleaf Birch', '2 Sherman Street', 'Jijia', null);
insert into plantation (id, id_user, name, address, city, state) values (137, 296, 'Stinging Phacelia', '0 Lyons Crossing', 'Pajé', null);
insert into plantation (id, id_user, name, address, city, state) values (138, 90, 'Fragrant Bugle-lily', '800 David Court', 'Zangbawa', null);
insert into plantation (id, id_user, name, address, city, state) values (139, 83, 'Blue Mountain Buckwheat', '4530 Judy Drive', 'Ariz', 'Porto');
insert into plantation (id, id_user, name, address, city, state) values (140, 14, 'Island Wallflower', '56 Bellgrove Way', 'Perelhal', 'Braga');
insert into plantation (id, id_user, name, address, city, state) values (141, 267, 'Skin Lichen', '479 Beilfuss Road', 'Sączów', null);
insert into plantation (id, id_user, name, address, city, state) values (142, 32, 'Lyreleaf Greeneyes', '7 Ilene Street', 'Sierakowice', null);
insert into plantation (id, id_user, name, address, city, state) values (143, 262, 'Spotted Stickseed', '11402 Stoughton Way', 'Yaozhanzi', null);
insert into plantation (id, id_user, name, address, city, state) values (144, 5, 'Manchurian Yellow Loosestrife', '7 Laurel Plaza', 'Basel', 'Kanton Basel-Stadt');
insert into plantation (id, id_user, name, address, city, state) values (145, 265, 'Smallhead Heathgoldenrod', '862 Sugar Road', 'Kokopo', null);
insert into plantation (id, id_user, name, address, city, state) values (146, 132, 'Coral Bristlegrass', '1 Lakeland Place', 'Fukuechō', null);
insert into plantation (id, id_user, name, address, city, state) values (147, 205, 'Marsh American-aster', '97 Forest Run Avenue', 'At-Bashi', null);
insert into plantation (id, id_user, name, address, city, state) values (148, 260, 'Pricklypoppy', '25832 Knutson Street', 'Khvānsār', null);
insert into plantation (id, id_user, name, address, city, state) values (149, 126, 'Congo Mahoe', '57879 Buhler Alley', 'Vatutino', null);
insert into plantation (id, id_user, name, address, city, state) values (150, 297, 'Liogier''s Dwarf Polypody', '21 Sherman Drive', 'Metallostroy', null);
insert into plantation (id, id_user, name, address, city, state) values (151, 123, 'Compact Prairie Clover', '39 Cody Drive', 'Pradera', null);
insert into plantation (id, id_user, name, address, city, state) values (152, 227, 'Limestone Draba', '8946 Dahle Pass', 'Haykashen', null);
insert into plantation (id, id_user, name, address, city, state) values (153, 10, 'Zelometeorium Moss', '72424 Hovde Point', 'Daye', null);
insert into plantation (id, id_user, name, address, city, state) values (154, 115, 'Black Cherry', '5308 Cherokee Trail', 'Khamyāb', null);
insert into plantation (id, id_user, name, address, city, state) values (155, 291, 'Ballhead Ipomopsis', '17 Stuart Terrace', 'Luodian', null);
insert into plantation (id, id_user, name, address, city, state) values (156, 191, 'Bristleleaf Pricklyleaf', '37044 Waubesa Avenue', 'Barnaul', null);
insert into plantation (id, id_user, name, address, city, state) values (157, 52, 'Melaspilea Lichen', '3 Brown Park', 'Cikiruh Wetan', null);
insert into plantation (id, id_user, name, address, city, state) values (158, 253, 'Johnston''s Cryptantha', '166 Gateway Terrace', 'Wuyang', null);
insert into plantation (id, id_user, name, address, city, state) values (159, 88, 'Kamchatka Rhododendron', '484 Sommers Junction', 'Barcelona', 'Cataluna');
insert into plantation (id, id_user, name, address, city, state) values (160, 225, 'Rim Lichen', '19 Monument Parkway', 'Pueblo Nuevo', null);
insert into plantation (id, id_user, name, address, city, state) values (161, 207, 'Hoary Fleabane', '38 Del Mar Plaza', 'Kamenka', null);
insert into plantation (id, id_user, name, address, city, state) values (162, 37, 'West Indian Tonguefern', '5671 Artisan Circle', 'Gozdnica', null);
insert into plantation (id, id_user, name, address, city, state) values (163, 283, 'Sharp-tooth Buckthorn', '9 Buell Crossing', 'Huanggangshan', null);
insert into plantation (id, id_user, name, address, city, state) values (164, 67, 'American Nailwort', '8 Weeping Birch Terrace', 'Fayzabad', null);
insert into plantation (id, id_user, name, address, city, state) values (165, 279, 'Common Pear', '010 Stang Trail', 'Shangtang', null);
insert into plantation (id, id_user, name, address, city, state) values (166, 192, 'Saltwater Bush', '720 Thackeray Road', 'Emalgolin Mongolzuxiang', null);
insert into plantation (id, id_user, name, address, city, state) values (167, 174, 'Littleleaf Minerslettuce', '03811 Colorado Place', 'Jackson', 'Mississippi');
insert into plantation (id, id_user, name, address, city, state) values (168, 165, 'Slender Woodland-star', '4451 Walton Drive', 'Borås', 'Västra Götaland');
insert into plantation (id, id_user, name, address, city, state) values (169, 168, 'Sinkwa Towelsponge', '2184 Banding Plaza', 'A dos Negros', 'Leiria');
insert into plantation (id, id_user, name, address, city, state) values (170, 88, 'Tall Draba', '759 Coleman Circle', 'Longquan', null);
insert into plantation (id, id_user, name, address, city, state) values (171, 6, 'Zahlbrucknerella Lichen', '060 Nobel Point', 'Lila', null);
insert into plantation (id, id_user, name, address, city, state) values (172, 68, 'Lemon-flower Gum', '5 Talisman Terrace', 'Carbonear', 'Newfoundland and Labrador');
insert into plantation (id, id_user, name, address, city, state) values (173, 273, 'Anomobryum Moss', '87564 Pawling Terrace', 'Horodnytsya', null);
insert into plantation (id, id_user, name, address, city, state) values (174, 151, 'Orange-flower Star Orchid', '01 Northridge Way', 'Upper San Mateo', null);
insert into plantation (id, id_user, name, address, city, state) values (175, 258, 'Helodium Moss', '44668 Coolidge Street', 'Il’skiy', null);
insert into plantation (id, id_user, name, address, city, state) values (176, 7, 'Na''ena''e Pua Melemele', '1 Lakewood Lane', 'San Francisco', null);
insert into plantation (id, id_user, name, address, city, state) values (177, 70, 'Scoliciosporum Lichen', '69 Merchant Hill', 'Praingkareha', null);
insert into plantation (id, id_user, name, address, city, state) values (178, 242, 'Bluehead Gilia', '3 Heath Hill', 'Czarnocin', null);
insert into plantation (id, id_user, name, address, city, state) values (179, 194, 'Dot Lichen', '12741 Buena Vista Place', 'Gondomar', 'Braga');
insert into plantation (id, id_user, name, address, city, state) values (180, 78, 'Arctic Starflower', '58 Longview Lane', 'Frederiksberg', 'Region Hovedstaden');
insert into plantation (id, id_user, name, address, city, state) values (181, 96, 'White Bryony', '087 Hoepker Crossing', 'Paris 11', 'Île-de-France');
insert into plantation (id, id_user, name, address, city, state) values (182, 212, 'Palo De Hueso', '3255 Sage Court', 'Kembangkerang Lauk Timur', null);
insert into plantation (id, id_user, name, address, city, state) values (183, 252, 'Wart Lichen', '94579 Kinsman Lane', 'Bokor', null);
insert into plantation (id, id_user, name, address, city, state) values (184, 7, 'Maui Phyllostegia', '544 Dennis Road', 'Bethlehem', 'Pennsylvania');
insert into plantation (id, id_user, name, address, city, state) values (185, 167, 'Sandhills Lily', '264 Brentwood Center', 'Černilov', null);
insert into plantation (id, id_user, name, address, city, state) values (186, 219, 'Flagstaff Ragwort', '6 Acker Crossing', 'San Rafael', null);
insert into plantation (id, id_user, name, address, city, state) values (187, 135, 'Rigiopappus', '68 Reindahl Junction', 'San Jose', null);
insert into plantation (id, id_user, name, address, city, state) values (188, 67, 'Ligulate Syrrhopodon Moss', '0199 Cody Junction', 'Tignoan', null);
insert into plantation (id, id_user, name, address, city, state) values (189, 204, 'Laurel', '1401 Northport Trail', 'Magdalena', null);
insert into plantation (id, id_user, name, address, city, state) values (190, 177, 'Hartweg''s Cyphomandra', '4799 Jana Court', 'Corcuera', null);
insert into plantation (id, id_user, name, address, city, state) values (191, 211, 'Dwarf Barley', '1 Jana Lane', 'Kiritsy', null);
insert into plantation (id, id_user, name, address, city, state) values (192, 121, 'Mojave Yucca', '1 Loeprich Circle', 'Caigangan', null);
insert into plantation (id, id_user, name, address, city, state) values (193, 168, 'Dwarf Red Blackberry', '58615 Gateway Drive', 'Forshaga', 'Värmland');
insert into plantation (id, id_user, name, address, city, state) values (194, 126, 'Field Sagewort', '7748 Fremont Junction', 'Telnice', null);
insert into plantation (id, id_user, name, address, city, state) values (195, 171, 'Anomodon Moss', '49 Sloan Crossing', 'Golubinci', null);
insert into plantation (id, id_user, name, address, city, state) values (196, 130, 'Ribbed Paspalum', '9 Ruskin Road', 'K’olīto', null);
insert into plantation (id, id_user, name, address, city, state) values (197, 243, 'Curtiss'' Evening Primrose', '702 Kensington Point', 'Cuevas', null);
insert into plantation (id, id_user, name, address, city, state) values (198, 275, 'Feltleaf Willow', '445 Heath Trail', 'Ostrožská Nová Ves', null);
insert into plantation (id, id_user, name, address, city, state) values (199, 111, 'Chicory', '214 Towne Street', 'Szczawnica', null);
insert into plantation (id, id_user, name, address, city, state) values (200, 59, 'Lama', '63668 Declaration Court', 'Krajan Kulon', null);
insert into plantation (id, id_user, name, address, city, state) values (201, 215, 'Tufted Globe Amaranth', '6167 Coolidge Drive', 'Jindayris', null);
insert into plantation (id, id_user, name, address, city, state) values (202, 198, 'Macrae''s Spleenwort', '9 Warbler Circle', 'Fayzabad', null);
insert into plantation (id, id_user, name, address, city, state) values (203, 293, 'Kauai Nehe', '85 Fremont Alley', 'Sāqayn', null);
insert into plantation (id, id_user, name, address, city, state) values (204, 113, 'Oakes'' Eyebright', '27850 Mayer Avenue', 'Karangarjo', null);
insert into plantation (id, id_user, name, address, city, state) values (205, 60, 'Tiny Purslane', '653 Morrow Lane', 'Tanahedang', null);
insert into plantation (id, id_user, name, address, city, state) values (206, 230, 'Amazonvine', '478 Larry Lane', 'Néa Karyá', null);
insert into plantation (id, id_user, name, address, city, state) values (207, 109, 'Gila Rockdaisy', '87 Jenifer Court', 'Kurbnesh', null);
insert into plantation (id, id_user, name, address, city, state) values (208, 243, 'Clustered Goldenweed', '9265 Grover Parkway', 'Kalamáta', null);
insert into plantation (id, id_user, name, address, city, state) values (209, 6, 'Husk Tomato', '12 Kenwood Point', 'Kajatian', null);
insert into plantation (id, id_user, name, address, city, state) values (210, 101, 'El Dorado Mule-ears', '83694 Kingsford Circle', 'Zishan', null);
insert into plantation (id, id_user, name, address, city, state) values (211, 100, 'Sematophyllum Moss', '209 Melvin Center', 'Gelan', null);
insert into plantation (id, id_user, name, address, city, state) values (212, 125, 'Giant Vetch', '51024 Sugar Point', 'Bayt Qād', null);
insert into plantation (id, id_user, name, address, city, state) values (213, 260, 'Reflexed Airplant', '89 Duke Alley', 'La Virgen', 'Mexico');
insert into plantation (id, id_user, name, address, city, state) values (214, 249, 'Sharpflower Rush', '3 Cambridge Street', 'Huichang', null);
insert into plantation (id, id_user, name, address, city, state) values (215, 263, 'Oat', '43 Corscot Road', 'Grenoble', 'Rhône-Alpes');
insert into plantation (id, id_user, name, address, city, state) values (216, 166, 'Rim Lichen', '29 Annamark Crossing', 'Port-aux-Français', null);
insert into plantation (id, id_user, name, address, city, state) values (217, 135, 'Hornemann''s Willowherb', '629 Eliot Center', 'Haghartsin', null);
insert into plantation (id, id_user, name, address, city, state) values (218, 184, 'Seasonvine', '5640 Orin Terrace', 'Amboasary', null);
insert into plantation (id, id_user, name, address, city, state) values (219, 91, 'Yellow Marsh Saxifrage', '07275 Sutherland Way', 'Messina', 'Sicilia');
insert into plantation (id, id_user, name, address, city, state) values (220, 211, 'Nodding Blue-eyed Grass', '70914 Old Gate Court', 'Tianta', null);
insert into plantation (id, id_user, name, address, city, state) values (221, 1, 'Silktassel', '04955 Sauthoff Court', 'Malummaduri', null);
insert into plantation (id, id_user, name, address, city, state) values (222, 190, 'Partridgeberry', '4275 Twin Pines Place', 'Al Muţayrifī', null);
insert into plantation (id, id_user, name, address, city, state) values (223, 243, 'Cracked Lichen', '6 Jenna Circle', 'Sinarjaya', null);
insert into plantation (id, id_user, name, address, city, state) values (224, 227, 'Homalia Moss', '3991 Schiller Terrace', 'Būrabay', null);
insert into plantation (id, id_user, name, address, city, state) values (225, 268, 'Jones'' Beardtongue', '8 Ridgeview Road', 'Masḩah', null);
insert into plantation (id, id_user, name, address, city, state) values (226, 48, 'Granite Mousetail', '74000 Sutteridge Pass', 'Hainan', null);
insert into plantation (id, id_user, name, address, city, state) values (227, 261, 'Rhizomnium Moss', '99 Lakewood Gardens Drive', 'Flic en Flac', null);
insert into plantation (id, id_user, name, address, city, state) values (228, 269, 'Matted Lichen', '38 Browning Way', 'Kudus', null);
insert into plantation (id, id_user, name, address, city, state) values (229, 249, 'Yellow Bloodstain Lichen', '98 Columbus Court', 'Joyabaj', null);
insert into plantation (id, id_user, name, address, city, state) values (230, 201, 'Hophornbeam', '2846 Oakridge Circle', 'Intendente Alvear', null);
insert into plantation (id, id_user, name, address, city, state) values (231, 62, 'Plains Beeblossom', '262 Waxwing Drive', 'Monte da Pedra', 'Portalegre');
insert into plantation (id, id_user, name, address, city, state) values (232, 74, 'Jeweled Stenogyne', '10618 Valley Edge Park', 'Semalang', null);
insert into plantation (id, id_user, name, address, city, state) values (233, 240, 'Tall Tonguefern', '84 Norway Maple Place', 'Taraz', null);
insert into plantation (id, id_user, name, address, city, state) values (234, 230, 'Forest Johnnyberry', '739 Bayside Circle', 'Matsuyama', null);
insert into plantation (id, id_user, name, address, city, state) values (235, 86, 'Engelmann''s Knotweed', '7486 Luster Lane', 'Padangtiji', null);
insert into plantation (id, id_user, name, address, city, state) values (236, 298, 'Soft Bird''s-beak', '95 Sunfield Plaza', 'Pinamalayan', null);
insert into plantation (id, id_user, name, address, city, state) values (237, 149, 'Erpodium Moss', '678 Main Terrace', 'Qinlan', null);
insert into plantation (id, id_user, name, address, city, state) values (238, 94, 'Longleaf Pine', '64760 Bluejay Plaza', 'Agen', 'Aquitaine');
insert into plantation (id, id_user, name, address, city, state) values (239, 286, 'Payson''s Tansymustard', '7214 Milwaukee Street', 'Pahing Pamulihan', null);
insert into plantation (id, id_user, name, address, city, state) values (240, 94, 'Slim Milkweed', '71362 Mitchell Park', 'Liujiagou', null);
insert into plantation (id, id_user, name, address, city, state) values (241, 195, 'Panamint Daisy', '7 Helena Alley', 'Shchelkovo', null);
insert into plantation (id, id_user, name, address, city, state) values (242, 135, 'Phaeographina Lichen', '5 Sycamore Park', 'Hawassa', null);
insert into plantation (id, id_user, name, address, city, state) values (243, 145, 'Wart Lichen', '53049 Michigan Alley', 'Jacksonville', 'Florida');
insert into plantation (id, id_user, name, address, city, state) values (244, 56, 'Dominican Lovegrass', '24 Cardinal Lane', 'Morant Bay', null);
insert into plantation (id, id_user, name, address, city, state) values (245, 298, 'Nevada Bird''s-foot Trefoil', '0 Evergreen Circle', 'Sinamaica', null);
insert into plantation (id, id_user, name, address, city, state) values (246, 298, 'California Blackberry', '3 Northwestern Court', 'Duyang', null);
insert into plantation (id, id_user, name, address, city, state) values (247, 241, 'Heliopsis', '4697 Larry Road', 'Bratislava', null);
insert into plantation (id, id_user, name, address, city, state) values (248, 70, 'Skunkbush Sumac', '0271 Vera Center', 'Newport News', 'Virginia');
insert into plantation (id, id_user, name, address, city, state) values (249, 268, 'Drushel''s Wild Petunia', '172 Truax Circle', 'Osiek', null);
insert into plantation (id, id_user, name, address, city, state) values (250, 298, 'Bigflower Tellima', '72191 Waywood Trail', 'Karlskoga', 'Örebro');
insert into plantation (id, id_user, name, address, city, state) values (251, 125, 'Swamp Larkspur', '99464 Pine View Point', 'Pignon', null);
insert into plantation (id, id_user, name, address, city, state) values (252, 274, 'Panamint Buckwheat', '17 Hoepker Hill', 'Del Valle', 'Veracruz Llave');
insert into plantation (id, id_user, name, address, city, state) values (253, 140, 'Brittle Spineflower', '6 Chinook Junction', 'Azaruja', 'Évora');
insert into plantation (id, id_user, name, address, city, state) values (254, 44, 'Kaibab Draba', '734 Jenna Court', 'Mae Lao', null);
insert into plantation (id, id_user, name, address, city, state) values (255, 80, 'Bollean Mistletoe', '39863 Spaight Place', 'Jovim', 'Porto');
insert into plantation (id, id_user, name, address, city, state) values (256, 97, 'Hypotrachyna Lichen', '383 Cascade Street', 'Sortavala', null);
insert into plantation (id, id_user, name, address, city, state) values (257, 70, 'Treasureflower', '79 Mccormick Center', 'Waitangi', null);
insert into plantation (id, id_user, name, address, city, state) values (258, 59, 'Native Caper', '52138 Thackeray Center', 'Wiang Chiang Rung', null);
insert into plantation (id, id_user, name, address, city, state) values (259, 271, 'Broadleaf Lupine', '6 Cambridge Way', 'Muang Sam Sip', null);
insert into plantation (id, id_user, name, address, city, state) values (260, 135, 'Butte Desertparsley', '596 Becker Park', 'Polyarnyye Zori', null);
insert into plantation (id, id_user, name, address, city, state) values (261, 158, 'Red Sand Verbena', '8 Ohio Circle', 'Kyankwanzi', null);
insert into plantation (id, id_user, name, address, city, state) values (262, 199, 'Smooth Violet Prairie Aster', '9 Weeping Birch Park', 'Malvas', null);
insert into plantation (id, id_user, name, address, city, state) values (263, 243, 'Pacific Jewelflower', '71290 Prentice Park', 'Mikulintsy', null);
insert into plantation (id, id_user, name, address, city, state) values (264, 213, 'Crimson Weigela', '95514 Brickson Park Street', 'Tianfu', null);
insert into plantation (id, id_user, name, address, city, state) values (265, 149, 'Timopheev''s Wheat', '9736 Judy Street', 'Washington', 'District of Columbia');
insert into plantation (id, id_user, name, address, city, state) values (266, 165, 'Thelenella Lichen', '530 Browning Alley', 'Igarapé', null);
insert into plantation (id, id_user, name, address, city, state) values (267, 293, 'Nevada Goosefoot', '084 Arapahoe Way', 'Cô Tô', null);
insert into plantation (id, id_user, name, address, city, state) values (268, 150, 'Cooper''s Popcornflower', '6552 Southridge Crossing', 'Toyokawa', null);
insert into plantation (id, id_user, name, address, city, state) values (269, 67, 'Beechey''s Bamboo', '54 Maple Wood Alley', 'Hongkou', null);
insert into plantation (id, id_user, name, address, city, state) values (270, 49, 'Rugulose Shield Lichen', '8746 Mcbride Drive', 'Oujiangcha', null);
insert into plantation (id, id_user, name, address, city, state) values (271, 237, 'Desert Ceanothus', '5497 Sutherland Terrace', 'Ulbroka', null);
insert into plantation (id, id_user, name, address, city, state) values (272, 161, 'Malaysian Persimmon', '438 Maryland Circle', 'Vukovar', null);
insert into plantation (id, id_user, name, address, city, state) values (273, 3, 'Texas Vervain', '2894 Anthes Alley', 'Jungutbatu Kaja Dua', null);
insert into plantation (id, id_user, name, address, city, state) values (274, 111, 'Snow Dwarf-primrose', '775 Straubel Crossing', 'Zhenchuan', null);
insert into plantation (id, id_user, name, address, city, state) values (275, 232, 'Bottlebrush', '1043 Starling Crossing', 'Néa Péramos', null);
insert into plantation (id, id_user, name, address, city, state) values (276, 120, 'Caloncoba', '0651 Arrowood Hill', 'Všeruby', null);
insert into plantation (id, id_user, name, address, city, state) values (277, 245, 'Brazilian Watergrass', '38 Basil Hill', 'Fangfan', null);
insert into plantation (id, id_user, name, address, city, state) values (278, 105, 'Jeweled Hawthorn', '0212 6th Avenue', 'Glubokiy', null);
insert into plantation (id, id_user, name, address, city, state) values (279, 250, 'Golden Suncup', '88181 Elka Road', 'Kolodenka', null);
insert into plantation (id, id_user, name, address, city, state) values (280, 191, 'Arctic Springbeauty', '7942 Vera Hill', 'Uenohara', null);
insert into plantation (id, id_user, name, address, city, state) values (281, 275, 'Oxypetalum', '77090 Monument Way', 'Watuagung', null);
insert into plantation (id, id_user, name, address, city, state) values (282, 41, 'Beard Lichen', '31 Union Hill', 'Falkenberg', 'Halland');
insert into plantation (id, id_user, name, address, city, state) values (283, 169, 'Trujillo Coca', '822 Cody Way', 'São Martinho do Campo', 'Porto');
insert into plantation (id, id_user, name, address, city, state) values (284, 33, 'Spiral Ditchgrass', '741 Melrose Lane', 'Dolní Dvořiště', null);
insert into plantation (id, id_user, name, address, city, state) values (285, 69, 'Canada Lily', '18344 Alpine Trail', 'Jiayuguan', null);
insert into plantation (id, id_user, name, address, city, state) values (286, 28, 'California Poppy', '551 Oak Place', 'Serra D''El Rei', 'Leiria');
insert into plantation (id, id_user, name, address, city, state) values (287, 141, 'Leafless Beaked Lady Orchid', '9514 Express Hill', 'Prilep', null);
insert into plantation (id, id_user, name, address, city, state) values (288, 193, 'Thimble Grass', '2 Myrtle Circle', 'Kropotkin', null);
insert into plantation (id, id_user, name, address, city, state) values (289, 127, 'Yerba De Guava', '4 Barby Street', 'Ladário', null);
insert into plantation (id, id_user, name, address, city, state) values (290, 136, 'Flatcrown Buckwheat', '6315 Truax Park', 'Bydgoszcz', null);
insert into plantation (id, id_user, name, address, city, state) values (291, 200, 'Star Tickseed', '64710 Anniversary Terrace', 'Pryluky', null);
insert into plantation (id, id_user, name, address, city, state) values (292, 43, 'Cutleaf False Oxtongue', '69 Carberry Park', 'Patea', null);
insert into plantation (id, id_user, name, address, city, state) values (293, 200, 'Castle Crags Bellflower', '5 Gulseth Park', 'Osa', null);
insert into plantation (id, id_user, name, address, city, state) values (294, 283, 'Narrowleaf Water-starwort', '10 Oxford Park', 'Shencang', null);
insert into plantation (id, id_user, name, address, city, state) values (295, 95, 'Newberry''s Twinpod', '835 8th Trail', 'Alīgūdarz', null);
insert into plantation (id, id_user, name, address, city, state) values (296, 238, 'Pacific Saxifrage', '20 Northland Terrace', 'Obanazawa', null);
insert into plantation (id, id_user, name, address, city, state) values (297, 1, 'Waterparsnip', '909 Stang Court', 'Colonia Neuland', null);
insert into plantation (id, id_user, name, address, city, state) values (298, 132, 'French Sorrel', '38 Division Street', 'Homeyo', null);
insert into plantation (id, id_user, name, address, city, state) values (299, 297, 'Fremont County Twinpod', '56 Morningstar Alley', 'Masatepe', null);
insert into plantation (id, id_user, name, address, city, state) values (300, 81, 'Sandwort Daisy Fleabane', '8 Larry Drive', 'Cuenca', null);
